services:
  mc:
    build: .
    network_mode: "host"
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
      MEMORY: "6144M"
      ONLINE_MODE: "false"
      SERVER_PORT: "8080"
      TZ: "Asia/Kolkata"
      PLUGINS: |-
        # plugin jar file download link here
    volumes:
      - "./data:/data"
